## Assignment No_2

In [ ]:
#Que:1 What are the two values of the Boolean data type? How do you write them?

In [ ]:
The two values of the Boolean data type are true and false.The result of a Boolean expression is either true or false.
Generally, it is used to represent the truth values of the expressions. For example, 1== 0 is True whereas 3<1 is False.

In [ ]:
#Que:2 What are the three different types of Boolean operators?

In [ ]:
The three different types of boolean operators are AND,OR and NOT.

In [ ]:
#Que:3 Make a list of each Boolean operator's truth tables 
#(i.e. every possible combination of Boolean values for the operator and what it evaluate ).

In [ ]:
AND            
T T = T
F T = F
T F = F
F F = F

OR
T T = T
F T = T
T F = T
F F = F

In [ ]:
#Que:4 What are the values of the following expressions?

In [1]:
(5 > 4) and (3 == 5)

False

In [2]:
not (5 > 4)

False

In [3]:
(5 > 4) or (3 == 5)

True

In [4]:
not ((5 > 4) or (3 == 5))

False

In [5]:
(True and True) and (True == False)

False

In [6]:
(not False) or (not True)

True

In [ ]:
#Que:5 What are the six comparison operators?

In [ ]:
There are six main comparison operators
equal to, not equal to, greater than,less than,greater than or equal to, and less than or equal to.

In [ ]:
#Que:6 How do you tell the difference between the equal to and assignment operators?
#Describe a condition and when you would use one.

In [1]:
The '==' is the so-called equality comparison operator and is used to check whether the two expressions
on both sides are equal or not.
The '=' is the so-called assignment operator and is used to assign the result of the expression on the 
right side of the operator to the variable on the left side. 

5==5
This will return true.

a=10.

In [ ]:
#Que:7 Identify the three blocks in this code:

In [ ]:
spam = 0
if spam == 10:
    print('eggs')
    if spam > 5:
        print('bacon')
    else:
        print('ham')
        print('spam')
        print('spam')

In [ ]:
print('eggs'),print('bacon'),print('ham')

In [1]:
#Que:8 Write code that prints Hello if 1 is stored in spam, prints Howdy if 2 is stored in spam, 
#and prints Greetings! if anything else is stored in spam.

In [ ]:
if spam = 1:
    print('Hello')   
elif spam = 2:
    print('Howdy')
else:
    print('Greetings')
        

In [ ]:
#Que:9 If your programme is stuck in an endless loop, what keys you’ll press?

In [ ]:
shift+tab

In [ ]:
#Que:10 How can you tell the difference between break and continue?

In [ ]:
Break leaves the loop completely and executes the statements after the loop.
Whereas Continue leaves the current iteration and executes with the next value in the loop. 
break completely exits the loop. continue skips the statements after the continue statement and keeps looping.

In [ ]:
#Que:11 In a for loop, what is the difference between range(10), range(0, 10), and range(0, 10, 1)?

In [5]:
import numpy as np

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0,10,4)

array([0, 4, 8])

range(10) and range(0, 10) are same but in lastone range(0, 10, 1) u will get the nos 0-10 in interval of 1 or u can put any no.

In [ ]:
#Que:12 Write a short program that prints the numbers 1 to 10 using a for loop. 
#Then write an equivalent program that prints the numbers 1 to 10 using a while loop.

In [31]:
# for loop
for v in range(0,11):
    print (v)

0
1
2
3
4
5
6
7
8
9
10


In [37]:
# while loop
v = 1
while(v<=10):
    print(v)
    v += 1


1
2
3
4
5
6
7
8
9
10


In [ ]:
#Que:13 If you had a function named bacon() inside a module named spam, how would you call it after importing spam?

In [13]:
import spam
spam.bacon()

ModuleNotFoundError: No module named 'spam'